name: Build and Deploy

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Update to the version that supports .NET 8.0

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./CalicotEncheres/Auctions

    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./CalicotEncheres/Auctions

    - name: Publish
      run: dotnet publish --configuration Release --output ./dist
      working-directory: ./CalicotEncheres/Auctions

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./CalicotEncheres/Auctions/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-calicot-dev-${{ secrets.CODE_IDENTIFICATION }}'
        slot-name: 'production'
        package: './dist'